backend/api/urls.py
from django.urls import path, include
from api.models import UserResource, FilesResource
from tastypie.api import Api

api = Api(api_name='v1')  # Добавляем версию api
user_resource = UserResource()
files_resource = FilesResource()
api.register(user_resource)
api.register(files_resource)


# api/v1/files/  GET, POST
# api/v1/files/1 GET, DELETE
# api/v1/users/  GET
# api/v1/users/1 GET

# Для POST, DELETE нужно добавить header
# Key: Authorization
# Value: ApiKey admin:apikeyforpostrequests

urlpatterns = [
    path('', include(api.urls), name='index')
]

backend/backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls'))
]

backend/backend/users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path('', views.index, name='index')
]

backend/mycloud/urls.py
from django.contrib import admin
from django.urls import path, include
from users.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('users.urls')),
    # path('api/', include(user_resource.urls)),
    path('api/', include('api.urls'))
]

# handler404 = "users.views.error_view"

backend/users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:files_id>', views.single_file, name='single_file')
]

backend/api/models.py
# from django.db import models
from tastypie.resources import ModelResource
from users.models import User, Files
from tastypie.authorization import Authorization
from .authentication import CustomAuthentication


class UserResource(ModelResource):
    class Meta:
        queryset = User.objects.all()
        resource_name = 'users'
        allowed_methods = ['get']


class FilesResource(ModelResource):
    class Meta:
        queryset = Files.objects.all()
        resource_name = 'files'
        allowed_methods = ['get', 'post', 'delete']
        # Скрываем в Json ненужные поля при необходимости
        excludes = ['link_download']
        authentication = CustomAuthentication()
        authorization = Authorization()

    # Для POST запроса создания файла нужно добавить id пользователя, к которому данный файл будет привязан,
    # но в модели Files нет поля user_id, чтобы обойти данную проблему нужно использовать следующие методы
    # hydrate - записываем в б.д. информацию полученную от пользователя (POST-запрос)
    # dehydrate - добавляет в JSON файл при выводе id пользователя к которому привязан конкретный файл (GET-запрос)

    def hydrate(self, bundle):
        bundle.obj.user_id = bundle.data['user_id']
        return bundle

    def dehydrate(self, bundle):
        bundle.data['user'] = bundle.obj.user
        bundle.data['user_id'] = bundle.obj.user_id
        return bundle

backend/backend/users/models.py
from django.db import models

# Create your models here.
# Функция создания пути к файлу путем имя пользователя(оно же название папки/ название файла)
def path_to_file(filename):
    user = User.login
    return f'{user}/{filename}'

class User(models.Model):
    login = models.CharField(max_length=20, primary_key=True, verbose_name='Логин')
    name = models.CharField(max_length=20, blank=False, verbose_name='Имя')
    password = models.CharField(max_length=50, verbose_name='Пароль')
    email = models.EmailField(max_length=50, verbose_name='Е-майл')
    is_admin = models.BooleanField(default=False, verbose_name='Администратор?')
    path_to_user = models.CharField(max_length=50, verbose_name='Путь к файлам пользователя')


class Files(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    title = models.CharField(max_length=100, unique=True, verbose_name='Название файла')
    description = models.TextField(blank=True, verbose_name='Описание')
    published = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')
    date_last_load = models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата последнего обновления')
    link_download = models.URLField(max_length=50, unique=True, blank=True, verbose_name="Прямая ссылка")
    path = models.FileField(upload_to=path_to_file, verbose_name='Путь к файлу')

backend/users/models.py
from django.db import models

# Функция создания пути к файлу путем имя пользователя(оно же название папки/ название файла)


# def path_to_file(filename):
#     print(filename)
#     print(User.login)
#     user = User.login
#     return f'{user}/{filename}'

def path_to_file(instance, filename):
    user_name = instance.user.name
    return f'storage/dir_{user_name}/{filename}'


class User(models.Model):
    login = models.CharField(unique=True,
                             max_length=20, verbose_name='Логин')
    name = models.CharField(max_length=20, blank=False, verbose_name='Имя')
    password = models.CharField(max_length=50, verbose_name='Пароль')
    email = models.EmailField(max_length=50, verbose_name='Е-майл')
    is_admin = models.BooleanField(
        default=False, verbose_name='Администратор?')
    path_to_user = models.CharField(
        max_length=50, verbose_name='Путь к файлам пользователя')

    def __str__(self):
        return self.login


class Files(models.Model):
    title = models.CharField(max_length=100, unique=True,
                             verbose_name='Название файла')
    description = models.TextField(blank=True, verbose_name='Описание')
    published = models.DateTimeField(
        auto_now_add=True, db_index=True, verbose_name='Дата создания')
    date_last_load = models.DateTimeField(
        auto_now=True, db_index=True, verbose_name='Дата последнего обновления')
    link_download = models.URLField(
        max_length=50, unique=True, blank=True, verbose_name="Прямая ссылка")
    path = models.FileField(upload_to=path_to_file,
                            verbose_name='Путь к файлу')
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name='Владелец файла')

    def __str__(self):
        return self.title

backend/api/views.py
from django.shortcuts import render

# Create your views here.

backend/backend/users/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse


def index(request):
    return HttpResponse("Hi!")

backend/users/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import User, Files


def index(request):
    files = Files.objects.all()
    # return HttpResponse(''.join([str(user) + '<br>' for user in users]))
    return render(request, 'users/files.html', {'files': files})


def single_file(request, files_id):
    file = get_object_or_404(Files, pk=files_id)
    return render(request, 'users/single_file.html', {'file': file})


# def error_view(request, exception):
#     return render(request, '404.html', status=404)

backend/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
  <nav class="navbar navbar-dark bg-dark">
    <div class="container">
      <a href={% url "users:index" %} class="navbar-brand">List of files</a>
      <span class="navbar-text">
        <a href="/admin/" class="me-2 target="_blank">Admin</a>
        <a href="/api/v1" target="_blank">API</a>
      </span>
    </div>
  </nav>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

backend/templates/users/files.html
{% extends 'base.html' %}

{% block title %}All files{% endblock %}

{% block content %}
<table class="table mt-5 table-bordered table-striped table-hover">
  <thead class="table-dark">
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Published</th>
      <th>Reload</th>
      <th>Link</th>
      <th>Path</th>
      <th>Owner</th>
    </tr>
  </thead>
  <tbody>
    {% for file in files %}    <tr>
      <td> 
        <a href={% url "users:single_file" file.id %}>{{ file.title }}</a>
      </td>
      <td>{{ file.description }}</td>
      <td>{{ file.published }}</td>
      <td>{{ file.date_last_load }}</td>
      <td>{{ file.link_download }}</td>
      <td>{{ file.path }}</td>
      <td>{{ file.user }}</td>
      <td><button class="btn btn-primary">Go to</button></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

backend/templates/users/single_file.html
{% extends 'base.html' %}

{% block title %}{{ file.title }}{% endblock %}

{% block content %}
<h1 class="mt-5">Название файла: {{ file.title }}</h1>
<h2>Описание: {{ file.description }}</h2>
<h3>Дата публикации: {{ file.published }}</h3>
<h3>Дата обновления: {{ file.date_last_load }}</h3>
<h3>Прямая ссылка: {{ file.link_download }}</h3>
<h3>Путь к файлу: {{ file.path }}</h3>
<h3>Владелец: {{ file.user }}</h3>
<button class="btn btn-primary">Go to</button>
{% endblock %}

backend/users/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
  <nav class="navbar navbar-dark bg-dark">
    <div class="container">
      <a href="" class="navbar-brand">List of files</a>
    </div>
  </nav>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

backend/users/templates/files.html
{% extends 'base.html' %}

{% block title %}All files{% endblock %}

{% block content %}
<table class="table mt-5 table-bordered table-striped table-hover">
  <thead class="table-dark">
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Published</th>
      <th>Reload</th>
      <th>Link</th>
      <th>Path</th>
      <th>Owner</th>
    </tr>
  </thead>
  <tbody>
    {% for file in files %}    <tr>
      <td>{{ file.title }}</td>
      <td>{{ file.description }}</td>
      <td>{{ file.published }}</td>
      <td>{{ file.date_last_load }}</td>
      <td>{{ file.link_download }}</td>
      <td>{{ file.path }}</td>
      <td>{{ file.user }}</td>
      <td><button class="btn btn-primary">Go to</button></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}